export const COLORS = [
  "secondary",
  "secondary bg-opacity-50",
  "secondary bg-opacity-10",
  "secondary bg-gradient",
  "danger",
  "danger bg-opacity-50",
  "danger bg-opacity-10",
  "danger bg-gradient",
  "warning",
  "warning bg-opacity-50",
  "warning bg-opacity-10",
  "warning bg-gradient",
  "success",
  "success bg-opacity-50",
  "success bg-opacity-10",
  "success bg-gradient",
  "primary",
  "primary bg-opacity-50",
  "primary bg-opacity-10",
  "primary bg-gradient",
  "info",
  "info bg-opacity-50",
  "info bg-opacity-10",
  "info bg-gradient",
];

export default COLORS;
